### ISSUE TITLE
JCH, Widgetkit, allow some Tools

### ISSUE THREAD

**Issue by lenusch** [nikosdion/kyrion-htaccess#4]
Hi, 
i tried to allow some tools (i.e. JCH Caching Plugin) but somehow gzip wont work for JCH generated Files. 

How can i add that? : ?
`RewriteRule ^cache\/widgetkit/ - [L]
RewriteRule ^cache\/com_zoo/ - [L]
RewriteRule ^cache\/com_templates/ - [L]
RewriteRule ^cache\/template/ - [L]
RewriteRule ^cache\/plg_jch_optimize/ - [L]`

is this correct?
`location ~* ^/cache\/widgetkit/ {
	break;
}
location ~* ^/cache\/com_zoo/ {
	break;
}
location ~* ^/cache\/com_templates/ {
	break;
}
location ~* ^/cache\/template/ {
	break;
}
location ~* ^/cache\/plg_jch_optimize/ {
	break;
}`

**Comment by nikosdion** [comment]
The hint pointing to the solution is on [line 309](https://github.com/nikosdion/master-htaccess/blob/master/htaccess.txt#L309)

You want to allow the directories `cache/com_zoo`, `cache/template`, `cache/com_templates` and `plg_jch_optimize` to the list of allowed folders. So, right below the comment you see in line 309 I linked above add the following:
```
RewriteRule ^cache/\com_zoo/ - [L]
RewriteRule ^cache/\template/ - [L]
RewriteRule ^cache/\com_templates/ - [L]
RewriteRule ^cache/\plg_jch_optimize/ - [L]
```

Please remember that the location of the directives in .htaccess is important! You MUST add these directives exactly where I told you, otherwise they might not work.

I would also like to point out that the code you added after "is this correct" in your message is actually NginX code which will not work inside .htaccess.

**Comment by lenusch** [comment]
Hi, thank you. 
My goal is to have that in NGINX not htaccess. 
your awesome htaccess i already have. 
But didnÄt found that in your NGINX Conf

**Comment by nikosdion** [comment]
It's the same as https://github.com/nikosdion/master-htaccess/blob/master/joomla.nginx.conf#L294

After line 287 add 
```
location ~* ^/cache/(com_zoo|com_templates|template|plg_jch_optimize)/.*.(jp(e?g|2)?|png|gif|bmp|css|js|swf|html?|ico|mpe(eg?[34])|avi|wav|og[gv]|xlsx?|docx?|pptx?|zip|rar|pdf|xps|txt|7z|svg|od[tsp]|flv|mov)$ {
		break;
}
```

This allows static files in these directories to be served. Please note that if it's .php files you need to serve from these folders you need to add a fastcgi_pass block before the break.
